import React from 'react';

export const TermsOfService = () => {
  return (
    <div className="max-w-4xl mx-auto p-8 pt-24 text-slate-300">
      <h1 className="text-3xl font-bold text-white mb-6">Terms of Service</h1>
      <p className="mb-4">Last updated: June 10, 2026</p>
      
      <h2 className="text-xl font-semibold text-white mt-6 mb-2">1. Acceptance of Terms</h2>
      <p className="mb-4">By accessing E2match.ai, you agree to be bound by these Terms of Service. Our predictions and AI analysis are for informational and entertainment purposes only.</p>

      <h2 className="text-xl font-semibold text-white mt-6 mb-2">2. No Betting Advice</h2>
      <p className="mb-4">E2match.ai is NOT a gambling or betting site. Any implied odds or predictions generated by our AI are simulations and do not guarantee real-world outcomes. We do not accept bets.</p>

      <h2 className="text-xl font-semibold text-white mt-6 mb-2">3. Limitation of Liability</h2>
      <p>We are not responsible for any financial losses or decisions made based on the information provided on this platform.</p>
    </div>
  );
};