// Corrected and expanded list of plausible 48 teams for the 2026 World Cup, distributed into 12 groups.
// Note: This is a fictional group draw for demonstration purposes.
export const WORLD_CUP_STANDINGS = [
  { groupName: 'Group A', entries: [{ rank: 1, teamName: 'Mexico', code: 'MEX', logo: '🇲🇽', played: 0, win: 0, draw: 0, lose: 0, goalsFor: 0, goalsAgainst: 0, gd: 0, points: 0 }, { rank: 2, teamName: 'South Africa', code: 'RSA', logo: '🇿🇦', played: 0, win: 0, draw: 0, lose: 0, goalsFor: 0, goalsAgainst: 0, gd: 0, points: 0 }, { rank: 3, teamName: 'South Korea', code: 'KOR', logo: '🇰🇷', played: 0, win: 0, draw: 0, lose: 0, goalsFor: 0, goalsAgainst: 0, gd: 0, points: 0 }, { rank: 4, teamName: 'Czechia', code: 'CZE', logo: '🇨🇿', played: 0, win: 0, draw: 0, lose: 0, goalsFor: 0, goalsAgainst: 0, gd: 0, points: 0 }] },
  { groupName: 'Group B', entries: [{ rank: 1, teamName: 'Canada', code: 'CAN', logo: '🇨🇦', played: 0, win: 0, draw: 0, lose: 0, goalsFor: 0, goalsAgainst: 0, gd: 0, points: 0 }, { rank: 2, teamName: 'Bosnia and Herzegovina', code: 'BIH', logo: '🇧🇦', played: 0, win: 0, draw: 0, lose: 0, goalsFor: 0, goalsAgainst: 0, gd: 0, points: 0 }, { rank: 3, teamName: 'Qatar', code: 'QAT', logo: '🇶🇦', played: 0, win: 0, draw: 0, lose: 0, goalsFor: 0, goalsAgainst: 0, gd: 0, points: 0 }, { rank: 4, teamName: 'Switzerland', code: 'SUI', logo: '🇨🇭', played: 0, win: 0, draw: 0, lose: 0, goalsFor: 0, goalsAgainst: 0, gd: 0, points: 0 }] },
  { groupName: 'Group C', entries: [{ rank: 1, teamName: 'Brazil', code: 'BRA', logo: '🇧🇷', played: 0, win: 0, draw: 0, lose: 0, goalsFor: 0, goalsAgainst: 0, gd: 0, points: 0 }, { rank: 2, teamName: 'Morocco', code: 'MAR', logo: '🇲🇦', played: 0, win: 0, draw: 0, lose: 0, goalsFor: 0, goalsAgainst: 0, gd: 0, points: 0 }, { rank: 3, teamName: 'Haiti', code: 'HAI', logo: '🇭🇹', played: 0, win: 0, draw: 0, lose: 0, goalsFor: 0, goalsAgainst: 0, gd: 0, points: 0 }, { rank: 4, teamName: 'Scotland', code: 'SCO', logo: '🏴󠁧󠁢󠁳󠁣󠁴󠁿', played: 0, win: 0, draw: 0, lose: 0, goalsFor: 0, goalsAgainst: 0, gd: 0, points: 0 }] },
  { groupName: 'Group D', entries: [{ rank: 1, teamName: 'United States', code: 'USA', logo: '🇺🇸', played: 0, win: 0, draw: 0, lose: 0, goalsFor: 0, goalsAgainst: 0, gd: 0, points: 0 }, { rank: 2, teamName: 'Paraguay', code: 'PAR', logo: '🇵🇾', played: 0, win: 0, draw: 0, lose: 0, goalsFor: 0, goalsAgainst: 0, gd: 0, points: 0 }, { rank: 3, teamName: 'Australia', code: 'AUS', logo: '🇦🇺', played: 0, win: 0, draw: 0, lose: 0, goalsFor: 0, goalsAgainst: 0, gd: 0, points: 0 }, { rank: 4, teamName: 'Türkiye', code: 'TUR', logo: '🇹🇷', played: 0, win: 0, draw: 0, lose: 0, goalsFor: 0, goalsAgainst: 0, gd: 0, points: 0 }] },
  { groupName: 'Group E', entries: [{ rank: 1, teamName: 'Germany', code: 'GER', logo: '🇩🇪', played: 0, win: 0, draw: 0, lose: 0, goalsFor: 0, goalsAgainst: 0, gd: 0, points: 0 }, { rank: 2, teamName: 'Curaçao', code: 'CUW', logo: '🇨🇼', played: 0, win: 0, draw: 0, lose: 0, goalsFor: 0, goalsAgainst: 0, gd: 0, points: 0 }, { rank: 3, teamName: 'Ivory Coast', code: 'CIV', logo: '🇨🇮', played: 0, win: 0, draw: 0, lose: 0, goalsFor: 0, goalsAgainst: 0, gd: 0, points: 0 }, { rank: 4, teamName: 'Ecuador', code: 'ECU', logo: '🇪🇨', played: 0, win: 0, draw: 0, lose: 0, goalsFor: 0, goalsAgainst: 0, gd: 0, points: 0 }] },
  { groupName: 'Group F', entries: [{ rank: 1, teamName: 'Netherlands', code: 'NED', logo: '🇳🇱', played: 0, win: 0, draw: 0, lose: 0, goalsFor: 0, goalsAgainst: 0, gd: 0, points: 0 }, { rank: 2, teamName: 'Japan', code: 'JPN', logo: '🇯🇵', played: 0, win: 0, draw: 0, lose: 0, goalsFor: 0, goalsAgainst: 0, gd: 0, points: 0 }, { rank: 3, teamName: 'Sweden', code: 'SWE', logo: '🇸🇪', played: 0, win: 0, draw: 0, lose: 0, goalsFor: 0, goalsAgainst: 0, gd: 0, points: 0 }, { rank: 4, teamName: 'Tunisia', code: 'TUN', logo: '🇹🇳', played: 0, win: 0, draw: 0, lose: 0, goalsFor: 0, goalsAgainst: 0, gd: 0, points: 0 }] },
  { groupName: 'Group G', entries: [{ rank: 1, teamName: 'Belgium', code: 'BEL', logo: '🇧🇪', played: 0, win: 0, draw: 0, lose: 0, goalsFor: 0, goalsAgainst: 0, gd: 0, points: 0 }, { rank: 2, teamName: 'Egypt', code: 'EGY', logo: '🇪🇬', played: 0, win: 0, draw: 0, lose: 0, goalsFor: 0, goalsAgainst: 0, gd: 0, points: 0 }, { rank: 3, teamName: 'IR Iran', code: 'IRN', logo: '🇮🇷', played: 0, win: 0, draw: 0, lose: 0, goalsFor: 0, goalsAgainst: 0, gd: 0, points: 0 }, { rank: 4, teamName: 'New Zealand', code: 'NZL', logo: '🇳🇿', played: 0, win: 0, draw: 0, lose: 0, goalsFor: 0, goalsAgainst: 0, gd: 0, points: 0 }] },
  { groupName: 'Group H', entries: [{ rank: 1, teamName: 'Spain', code: 'ESP', logo: '🇪🇸', played: 0, win: 0, draw: 0, lose: 0, goalsFor: 0, goalsAgainst: 0, gd: 0, points: 0 }, { rank: 2, teamName: 'Cabo Verde', code: 'CPV', logo: '🇨🇻', played: 0, win: 0, draw: 0, lose: 0, goalsFor: 0, goalsAgainst: 0, gd: 0, points: 0 }, { rank: 3, teamName: 'Saudi Arabia', code: 'KSA', logo: '🇸🇦', played: 0, win: 0, draw: 0, lose: 0, goalsFor: 0, goalsAgainst: 0, gd: 0, points: 0 }, { rank: 4, teamName: 'Uruguay', code: 'URU', logo: '🇺🇾', played: 0, win: 0, draw: 0, lose: 0, goalsFor: 0, goalsAgainst: 0, gd: 0, points: 0 }] },
  { groupName: 'Group I', entries: [{ rank: 1, teamName: 'France', code: 'FRA', logo: '🇫🇷', played: 0, win: 0, draw: 0, lose: 0, goalsFor: 0, goalsAgainst: 0, gd: 0, points: 0 }, { rank: 2, teamName: 'Senegal', code: 'SEN', logo: '🇸🇳', played: 0, win: 0, draw: 0, lose: 0, goalsFor: 0, goalsAgainst: 0, gd: 0, points: 0 }, { rank: 3, teamName: 'Iraq', code: 'IRQ', logo: '🇮🇶', played: 0, win: 0, draw: 0, lose: 0, goalsFor: 0, goalsAgainst: 0, gd: 0, points: 0 }, { rank: 4, teamName: 'Norway', code: 'NOR', logo: '🇳🇴', played: 0, win: 0, draw: 0, lose: 0, goalsFor: 0, goalsAgainst: 0, gd: 0, points: 0 }] },
  { groupName: 'Group J', entries: [{ rank: 1, teamName: 'Argentina', code: 'ARG', logo: '🇦🇷', played: 0, win: 0, draw: 0, lose: 0, goalsFor: 0, goalsAgainst: 0, gd: 0, points: 0 }, { rank: 2, teamName: 'Algeria', code: 'ALG', logo: '🇩🇿', played: 0, win: 0, draw: 0, lose: 0, goalsFor: 0, goalsAgainst: 0, gd: 0, points: 0 }, { rank: 3, teamName: 'Austria', code: 'AUT', logo: '🇦🇹', played: 0, win: 0, draw: 0, lose: 0, goalsFor: 0, goalsAgainst: 0, gd: 0, points: 0 }, { rank: 4, teamName: 'Jordan', code: 'JOR', logo: '🇯🇴', played: 0, win: 0, draw: 0, lose: 0, goalsFor: 0, goalsAgainst: 0, gd: 0, points: 0 }] },
  { groupName: 'Group K', entries: [{ rank: 1, teamName: 'Portugal', code: 'POR', logo: '🇵🇹', played: 0, win: 0, draw: 0, lose: 0, goalsFor: 0, goalsAgainst: 0, gd: 0, points: 0 }, { rank: 2, teamName: 'Congo DR', code: 'COD', logo: '🇨🇩', played: 0, win: 0, draw: 0, lose: 0, goalsFor: 0, goalsAgainst: 0, gd: 0, points: 0 }, { rank: 3, teamName: 'Uzbekistan', code: 'UZB', logo: '🇺🇿', played: 0, win: 0, draw: 0, lose: 0, goalsFor: 0, goalsAgainst: 0, gd: 0, points: 0 }, { rank: 4, teamName: 'Colombia', code: 'COL', logo: '🇨🇴', played: 0, win: 0, draw: 0, lose: 0, goalsFor: 0, goalsAgainst: 0, gd: 0, points: 0 }] },
  { groupName: 'Group L', entries: [{ rank: 1, teamName: 'England', code: 'ENG', logo: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', played: 0, win: 0, draw: 0, lose: 0, goalsFor: 0, goalsAgainst: 0, gd: 0, points: 0 }, { rank: 2, teamName: 'Croatia', code: 'CRO', logo: '🇭🇷', played: 0, win: 0, draw: 0, lose: 0, goalsFor: 0, goalsAgainst: 0, gd: 0, points: 0 }, { rank: 3, teamName: 'Ghana', code: 'GHA', logo: '🇬🇭', played: 0, win: 0, draw: 0, lose: 0, goalsFor: 0, goalsAgainst: 0, gd: 0, points: 0 }, { rank: 4, teamName: 'Panama', code: 'PAN', logo: '🇵🇦', played: 0, win: 0, draw: 0, lose: 0, goalsFor: 0, goalsAgainst: 0, gd: 0, points: 0 }] }
];

export const TRANSLATIONS = { en: {} };